version: '3'

volumes:
  db-data:
    driver: 'local'
  bundle-data:
    driver: 'local'
  node_modules-data:
    driver: 'local'

services:
  db:
    image: postgres:13.4-buster
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'testtest'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DB_HOST: 'db'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'testtest'
      DB_PORT: '5432'
      RAILS_ENV: 'development'
    volumes:
      - bundle-data:/app/vendor/bundle
    depends_on:
      - db
  web:
    ports:
      - '8080:3000'
    environment:
      NODE_ENV: 'development'
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - node_modules-data:/app/node_modules
    depends_on:
      - api
